routes/web.php
<?php

use App\Model\Page;
/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});
*/
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();
    if (Schema::hasTable('pages')) {
        $pages = Page::where('parent_id', NULL)->get();
        foreach ($pages as $page) {
            Route::get($page->slug, function () use ($page) {
                return view('content', ['page' => $page]);
            })->name($page->slug);
        }
    }
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'home']);
    Route::get('/glavnaya', function(){return redirect('');});
    Route::get('/parser', 'ParserController@parse');
    Route::resource('/cart','CartController');
    Route::get('/callback', 'CallbackController@callback');
    Route::get('/sitemap.xml', 'SitemapController@sitemap');

    /**Wishlist routes**/
    Route::get('/wishlist','WishlistController@index')->name('wishlist');
    Route::post('/wishlist','WishlistController@store')->name('wishlist.store');
    Route::post('/wishlist/destroy','WishlistController@destroy');
    Route::post('/wishlist/buyall','WishlistController@buyAll');

    /**Get single product*/
    Route::get('/products/{slug}', ['uses' => 'CatalogController@view', 'as' => 'product']);
    /**Get category*/
    Route::get('/catalog/{slug?}',['uses' => 'CatalogController@index', 'as' => 'catalog'] );
    Route::get('/tags/{slug}',['uses' => 'CatalogController@index', 'as' => 'tag'] );
    /*Order routes*/
    Route::get('order', 'OrderController@index')->name('order');
    Route::post('order/step3', 'OrderController@step3');
    Route::post('order/step4', 'OrderController@step4');
    Route::post('order/finish', 'OrderController@finish');
    /*Blog routes*/
    Route::get('/blog', 'BlogController@index')->name('blog');
    Route::get('/blog/{slug}', 'BlogController@view')->name('post');

    Route::get('/search','CatalogController@search')->name('search');
    Route::post('/filter', 'CatalogController@list');
    Route::get('/getbypid', 'CatalogController@getProductById');
    Route::get('register/confirm/{token}',[
        'as' => 'confirmation',
        'uses' => 'Auth\RegisterController@confirm'
    ]);

    /**Profile routes**/
    Route::get('/profile','ProfileController@index')->name('profile')->middleware('auth');
    Route::post('/profile','ProfileController@store')->middleware('auth');
    Route::post('/profile/changepassword','ProfileController@changePassword');

    /*Images routes*/
    Route::get('/images/{dateImg}/{filename}/{width}/{height}/{type?}/{anchor?}', 'ImageController@whResize');
    Route::get('/images/{dateImg}/{filename}/', 'ImageController@fullImage');

    /**Subscribe routes**/
    Route::post('/subscribe','SubscribeController@subscribe');
    Route::get('/subscribe/confirm/{token}','SubscribeController@confirm');
});
Route::get('api/orders/','ApiController@getOrders');
Route::post('api/users/','ApiController@getUsers');

resources/views/product/details.blade.php
@extends('layouts.app')

@section('content')
    {!! Breadcrumbs::renderIfExists('product', $product) !!}
        @include('includes/details')
        <section class="popular carousel">
            <h2 class="section-title">Рекомендуем</h2>
            
            <div class="items-carousel js-items-carousel">
                @foreach($recommends as $product)
                    @include('product.product')
                @endforeach
            </div>

        </section>        
        @if(!empty($lastviews) && !Agent::isMobile())

            <section class="last-views">
                <div class="header">
                    <div class="row">
                        <div class="col-xs-10">
                            <h4>НЕДАВНО ПРОСМОТРЕННОЕ</h4>
                        </div>
                        <div class="col-xs-2 text-right">
                            <div class="arrows"></div>
                        </div>
                    </div>
                </div>
                
                <div class="views-carousel">
                    @foreach($lastviews as $product)
                        <div class="views-item">
                            <div class="row">
                                <div class="col-sm-4">
                                    <a href="/products/{{$product->slug}}"><img src="/{{$product->resized('150x150')[0]}}" alt="" class="img-responsive"></a>
                                </div>
                                <div class="col-sm-8">
                                    <p class="title">
                                        <a href="/products/{{$product->slug}}">{{$product->title}}</a>
                                    </p>
                                    <p class="subtitle">
                                        {{$product->vid}} {{$product->gender}}
                                    </p>
                                    <p class="price">
                                        {{$product->price}} <i class="fa fa-rouble"></i>
                                    </p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </section>
        @endif
        
        <!--section class="seo">
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur</p>
        </section-->
        
@endsection    
@section('js')
@parent
    <script>
        $('.main-image').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
            fade: true,
            slide: '.slide',
            asNavFor: '.thumbs',
            autoplay: true,
            //adaptiveHeight: true,
            autoplaySpeed: 3000,
        });
        $('.thumbs').slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            asNavFor: '.main-image',
            dots: false,
            vertical: false,
            verticalSwiping:true,
            infinite: true,
            adaptiveHeight: true,
            focusOnSelect: true,
            arrows: false,
        });   

        $('.views-carousel').slick({
            infinite: true,
            dots: false,
            slidesToShow: 3,
            autoplay: false,
            slidesToScroll: 1,
            appendArrows: '.arrows',
            prevArrow:'<button type="button" class="slick-prev"><i class="fa fa-caret-left" aria-hidden="true"></i></button>',
            nextArrow:'<button type="button" class="slick-next"><i class="fa fa-caret-right" aria-hidden="true"></i></button>',
        });
    </script>
@endsection  

resources/views/product/modalproduct.blade.php
        <div class="container">
            @include('includes.details')
        </div>

resources/views/product/product-list.blade.php
                <div class="item {{$product->gender}} list" data-pid="{{$product->id}}">
                    @if($product->new)
                        <div class="new">NEW</div>
                    @endif
                    @if($product->price_sale>0)
                        <div class="sale"></div>
                    @endif
                    <div class="row">
                        <div class="col-xs-3">
                            <div class="image">
                                <a href="/products/{{$product->slug}}" data-pid="{{$product->id}}">
                                    <img src="/{{$product->resized('300x300')[0]}}" alt="{{$product->title}}" class="img-responsive">
                                </a>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="content">
                                <a class="wishlist js-wishlist  @if(session()->has('wishlist')) @if(in_array($product->id, session()->get('wishlist'))) active @endif @endif" href="#" data-pid="{{$product->id}}"></a>

                                <p class="title"><a href="/products/{{$product->slug}}">{{$product->title}}</a></p>
                                <p class="description">{{$product->vid}} {{$product->gender}}</p>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="shop-block">
                                <div class="price-block reg">
                                    <span class="price-type">
                                        {{--опт.:</span><span class="price">{{$product->price}} <i class="fa fa-rub" aria-hidden="true"></i>--}}
                                        Цена скрыта
                                    </span>
                                </div>
                                <div class="buy-block">
                                    <form action="{{route('cart.store')}}" method="POST" class="buy-form js-cart-add-form" data-pid="{{$product->id}}">
                                        {!! csrf_field() !!}
                                        <input type="hidden" value="{{$product->id}}" name="pid" class="pid">
                                        <input type="hidden" value="1" name="count">
                                        <button type="submit" class="btn btn-buy js-cart-add">В КОРЗИНУ</button>
                                    </form>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>

                    </div>
                </div>

resources/views/product/product.blade.php
                <div class="item {{$product->gender}}" data-pid="{{$product->id}}">
                    @if($product->new==1)
                        <div class="new">NEW</div>
                    @endif
                    @if($product->price_sale>0)
                        <div class="sale"></div>
                    @endif
                    <a class="wishlist js-wishlist  @if(session()->has('wishlist')) @if(in_array($product->id, session()->get('wishlist'))) active @endif @endif" href="#" data-pid="{{$product->id}}"></a>
                    <div class="image">
                        <a href="/products/{{$product->slug}}">
                            @if(Agent::isDesktop())
                                <div class="js-fastview fastview" data-pid="{{$product->id}}"></div>
                            @endif
                            <img src="/{{$product->resized('300x300')[0]}}" alt="{{$product->title}}" class="img-responsive">
                        </a>
                    </div>
                    <div class="content">
                        <p class="title"><a href="/products/{{$product->slug}}">{{$product->title}}</a></p>
                        <p class="description">{{$product->vid}}</p>
                    </div>
                    <div class="shop-block">

                        <div class="price-block reg">
                            <span class="price-type">
                                {{--опт.:</span><span class="price">{{$product->price}} <i class="fa fa-rub" aria-hidden="true"></i>--}}
                                Цена скрыта
                            </span>
                        </div>
                        {{--
                            <div class="price-block">
                                <div class="">
                                    <span class="price">{{$product->price_opt}} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                    @if($product->old_price>0)
                                        <span class="old-price">{{$product->old_price}} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                    @endif
                                </div>
                            </div>

                            @else
                                @if(Auth::user()->opt==1)
                                    <div class="price-block reg">
                                        <span class="price-type">опт.:</span><span class="price">{{$product->price}} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                    </div>
                                @else
                                    <div class="price-block reg">
                                        <!--span class="price-type">розн.:</span-->
                                        <span class="price">{{$product->price}} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                        @if($product->old_price>0)
                                            <span class="old-price">{{$product->old_price}} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                        @endif
                                    </div>
                                @endif
                            @endif
                            --}}
                        <div class="buy-block">
                            <form action="{{route('cart.store')}}" method="POST" class="buy-form js-cart-add-form" data-pid="{{$product->id}}">
                                {!! csrf_field() !!}
                                <input type="hidden" value="{{$product->id}}" name="pid" class="pid">
                                <input type="hidden" value="1" name="count">
                                <button type="submit" class="btn btn-buy js-cart-add">В КОРЗИНУ</button>
                            </form>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>